### ISSUE TITLE
BEM vs БЭМ

### ISSUE THREAD

**Issue by iamstarkov** [FrontenderMagazine/bem-css-methodology-complete-guide#3]
В статье на русском языке кажется лучше использовать русско-язычный термин, иначе многие будут читать как «вем»

**Comment by matmuchrapna** [comment]
пинг

**Comment by delka** [comment]
Но Яндекс всегда поправляет и требует именно "BEM", а не "БЭМ", Мурся меня несколько на поправляла в твиттере.

**Comment by matmuchrapna** [comment]
Предлагаю не подменять сообщество яндексом.

Мне кажется правильнее в русском контексте использовать русскую аббревиатуру БЭМ, особенно учитывая вероятность неправильного прочтения

@SilentImp @subzey @lancedikson @mursya @shuvalov-anton @delka, что думаете вы?

**Comment by lancedikson** [comment]
Полностью согласен с @matmuchrapna

**Comment by subzey** [comment]
Плюс один. В [русскоязычном твиттере](http://twitter.com/bem_ru) и на [офсайте](https://ru.bem.info/) используются русские буквы.

**Comment by iamstarkov** [comment]
вот и решили

**Comment by delka** [comment]
Кстати теперь Яндекс развернулся на 180 и требует писать «БЭМ».
Мурся перед моим докладом в Одессе многократно напоминала чтоб везде-везде на сладйдах «BEM» было заменено на «БЭМ».
Оставил „BEM“ только для „BEM CSS“

**Comment by iamstarkov** [comment]
если ты поменял на БЭМ, то наверное можно закрыть ишью, а не открыть
